#
#  ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ ███████╗
# ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ ██╔════╝
# ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗███████╗
# ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║╚════██║
# ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝███████║
#  ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝ ╚══════╝
#

name: Static Jekyll Project
exclude:
  - node_modules
  - _notes
  - gulpfile.js
  - package.json
  - package-lock.json
  - README.md
  - "*.zip"
  - "*.tmp"
# include:
#   - .htacess
# keep_files:
#   - ""
baseurl: "/"
destination: "_lp"
incremental: true
sass:
  sass_dir: _sass.tmp
# pagination:
#   enabled: true
#   per_page: 12
#   sort_reverse: true
#   limit: 0
#   sort_field: 'date'
#   permalink: '/page/:num/'
#   title: ':title'
#   trail:
#     before: 2
#     after: 2

#
# ██████╗ ███████╗███████╗ ██████╗██████╗ ██╗██████╗ ████████╗██╗ ██████╗ ███╗   ██╗███████╗
# ██╔══██╗██╔════╝██╔════╝██╔════╝██╔══██╗██║██╔══██╗╚══██╔══╝██║██╔═══██╗████╗  ██║██╔════╝
# ██║  ██║█████╗  ███████╗██║     ██████╔╝██║██████╔╝   ██║   ██║██║   ██║██╔██╗ ██║███████╗
# ██║  ██║██╔══╝  ╚════██║██║     ██╔══██╗██║██╔═══╝    ██║   ██║██║   ██║██║╚██╗██║╚════██║
# ██████╔╝███████╗███████║╚██████╗██║  ██║██║██║        ██║   ██║╚██████╔╝██║ ╚████║███████║
# ╚═════╝ ╚══════╝╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝╚═╝        ╚═╝   ╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝
#
#

project:
  type:
  description:
  features:
  info:
    url:

#
# ████████╗ █████╗  ██████╗ ███████╗
# ╚══██╔══╝██╔══██╗██╔════╝ ██╔════╝
#    ██║   ███████║██║  ███╗███████╗
#    ██║   ██╔══██║██║   ██║╚════██║
#    ██║   ██║  ██║╚██████╔╝███████║
#    ╚═╝   ╚═╝  ╚═╝ ╚═════╝ ╚══════╝
#
#

tag:
  gtm: # GTM-
  ss_tracking_code: #>

  adobe_font: #>

#
# ██╗     ██╗██████╗ ███████╗
# ██║     ██║██╔══██╗██╔════╝
# ██║     ██║██████╔╝███████╗
# ██║     ██║██╔══██╗╚════██║
# ███████╗██║██████╔╝███████║
# ╚══════╝╚═╝╚═════╝ ╚══════╝
#
#

libs:
  css:
    - ./css/main.css
  js:
    # - ./node_modules/jquery/dist/jquery.min.js
    # - ./node_modules/bootstrap/dist/js/bootstrap.min.js
    # - ./node_modules/waypoints/lib/jquery.waypoints.js
    # - ./node_modules/modal-video/js/jquery-modal-video.js
    # - ./node_modules/wowjs/dist/wow.min.js
    # - ./node_modules/jquery-modal/jquery.modal.min.js
    
    - ./node_modules/material-design-lite/material.min.js    
    - ./_js/main.js


#
# ███████╗███╗   ██╗██╗   ██╗███████╗
# ██╔════╝████╗  ██║██║   ██║██╔════╝
# █████╗  ██╔██╗ ██║██║   ██║███████╗
# ██╔══╝  ██║╚██╗██║╚██╗ ██╔╝╚════██║
# ███████╗██║ ╚████║ ╚████╔╝ ███████║
# ╚══════╝╚═╝  ╚═══╝  ╚═══╝  ╚══════╝
#
#

env:
  local:
    name: local
    url: http://192.168.15.96:3000/
  remote:
    remote:
    url: https://vmware.ingrammicro.com.br/vcpp/

#
# ██████╗  █████╗ ████████╗██╗  ██╗███████╗
# ██╔══██╗██╔══██╗╚══██╔══╝██║  ██║██╔════╝
# ██████╔╝███████║   ██║   ███████║███████╗
# ██╔═══╝ ██╔══██║   ██║   ██╔══██║╚════██║
# ██║     ██║  ██║   ██║   ██║  ██║███████║
# ╚═╝     ╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚══════╝
#
#

paths:
  img:
    url: images/
#
#  ██████╗ ██████╗ ██╗     ██╗     ███████╗ ██████╗████████╗██╗ ██████╗ ███╗   ██╗███████╗
# ██╔════╝██╔═══██╗██║     ██║     ██╔════╝██╔════╝╚══██╔══╝██║██╔═══██╗████╗  ██║██╔════╝
# ██║     ██║   ██║██║     ██║     █████╗  ██║        ██║   ██║██║   ██║██╔██╗ ██║███████╗
# ██║     ██║   ██║██║     ██║     ██╔══╝  ██║        ██║   ██║██║   ██║██║╚██╗██║╚════██║
# ╚██████╗╚██████╔╝███████╗███████╗███████╗╚██████╗   ██║   ██║╚██████╔╝██║ ╚████║███████║
#  ╚═════╝ ╚═════╝ ╚══════╝╚══════╝╚══════╝ ╚═════╝   ╚═╝   ╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝
#
#

# collections:
#   produtos-e-solucoes:
#     output: true
#     permalink: /:collection/:title/
#   fique-por-dentro:
#     output: true
#     permalink: /:collection/:title/
#   servicos-avancados:
#     output: true
#     permalink: /:collection/:title/
#   qualificacoes:
#   output: true
#   permalink: /:collection/:title/

#
# ██████╗ ███████╗███████╗ █████╗ ██╗   ██╗██╗  ████████╗███████╗
# ██╔══██╗██╔════╝██╔════╝██╔══██╗██║   ██║██║  ╚══██╔══╝██╔════╝
# ██║  ██║█████╗  █████╗  ███████║██║   ██║██║     ██║   ███████╗
# ██║  ██║██╔══╝  ██╔══╝  ██╔══██║██║   ██║██║     ██║   ╚════██║
# ██████╔╝███████╗██║     ██║  ██║╚██████╔╝███████╗██║   ███████║
# ╚═════╝ ╚══════╝╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝   ╚══════╝
#
#

# defaults:
#   -
#     scope:
#       path: ""
#       type: "produtos-e-solucoes"
#     values:
#       layout: default
#   -
#     scope:
#       path: ""
#       type: "qualificacoes"
#     values:
#       layout: default
#   -
#     scope:
#       path: ""
#       type: "fique-por-dentro"
#     values:
#       layout: default
#   -
#     scope:
#       path: ""
#       type: "servicos-avancados"
#     values:
#       layout: default
